spring:
  application:
    name: manage-config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ljyhust/running_snail
          uri: file:///E:/JAVA/GitHubCode/running_snail
          search-paths: manage_config_repo

server:
  port: 10010

security:
  basic:
    enabled: true
  user:
    name: ${CONFIG_USERNAME:user}
    password: ${CONFIG_PASSWORD:admin}


