spring:
  application:
    name: manage-config
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ljyhust/running_snail
          uri: file:///E:/JAVA/GitHubCode/running_snail
          search-paths: manage_config_repo

server:
  port: 10010

security:
  basic:
    enabled: true
  user:
    name: ${CONFIG_USERNAME:user}
    password: ${CONFIG_PASSWORD:admin}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${REGISTRY_USERNAME:user}:${REGISTRY_PASSWORD:admin}@192.168.2.21:10011/eureka/

