spring:
  application:
    name: manage_config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ljyhust/running_snail
          search-paths: manage_config_repo
server:
  port: 10010

