spring:
  application:
    name: manage-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ljyhust/running_snail
          search-paths: manage_config_repo

server:
  port: 10010

security:
  basic:
    enabled: true
  user:
    name: ${CONFIG_USERNAME:user}
    password: ${CONFIG_PASSWORD:admin}

eureka:
  instance:
    prefer-ip-address: true
    hostname: manage-config
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_USERNAME:user}:${REGISTRY_PASSWORD:admin}@manage-registry:10011/eureka/
